print('Base Camp Coffee Shop Simulator 4000, Version 1.00')
print('Copyright (C) 2024 BaseCamp Media, All Rights Reserved.')
print()
print("Let's collect some information before we start the game.")
print()   
name=input('What is your name? ')
shop_name=input('''What do you want to name your coffee shop? ''')
print()
print("Thanks, "+name+ ". Let's set some initial pricing.\n")
price=input('What do you want to charge per cup of coffee? ')
print("\nGreat. Here's what we've collected so far.")
print()
print('Your name is ' +name, "and you're opening " +shop_name+"!"),print("Your first cup of coffee will sell for $" +price+'.')