
print("""Welcome to the Ms. Frizzle's Digital Quiz Quest!

Get ready to test your knowledge and have some fun.
Whether you're here to challenge yourself or just pass the time,
we've got a range of questions to keep you on your toes.

Good luck, and may the best brain win!
""")    

print("1. How do you display a message to the user in Python?")
print("a) show()")
print("b) echo()")
print("c) print()")
print("d) display()")
print()
input("Enter your answer: ")
print("Correct Answer: c)")
print()
print("2. Which line of code prints Hello world! as one line of output?")
print("a) print(Hello world!)")
print('b) print("Hello", "world", "!")')
print('c) print("Hello world!")')
print('d) print("hello world")')
print()
input("Enter your answer: ")
print("Correct Answer: c)")
print()
print('3. Which lines of code prints Hello world! as one line of output?')
print('a) print("Hello")')
print('   print(" world!")')
print('b) print("Hello")')
print('   print(" world!", end="")')
print('c) print("Hello", sep="")')
print('   print(" world!")')
print('d) print("Hello", end="")')
print('   print(" world!")')
print()
input("Enter your answer: ")
print("Correct Answer: d)")
print()
print('4. What output is produced by the following statement?')
print('print("555", "0123", sep="-")')
print('a) 555 0123')
print('b) 555-0123')
print('c) 5550123-')
print('d) 5-5-5-0-1-2-3')
print()
input('Enter your answer: ')
print('Correct Answer: b)')
print()
print('5. In Python 3, which function is used to accept input from the user?')  
print('a) input()')
print('b) raw_input()')
print('c) rawinput()')
print('d) string()')
print()
input('Enter your answer: ')
print('Correct Answer: a)')
